### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Soonic1k** [Soonic1k/FileOrganizer#1]
- [x] List and return all files and folders
- [x] Move all files from root to specifically folder
- [x] Define a prefix/sufix automatically
- [x] Create a interface
